CC = clang
PYTHON_INCLUDE = -I /Users/abhiksarkar/opt/anaconda3/include/python3.9

hello: hello.c 
	$(CC) $(PYTHON_INCLUDE) -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/abhiksarkar/opt/anaconda3/include -arch arm64 -I/Users/abhiksarkar/opt/anaconda3/include -fPIC -O2 -isystem /Users/abhiksarkar/opt/anaconda3/include -arch arm64 -I/Users/abhiksarkar/opt/anaconda3/include/python3.9 -c hello.c -o hello
