CC = clang
PYTHON_INCLUDE = -I /Users/abhiksarkar/opt/anaconda3/include/python3.9

hello: hello.c 
	$(CC) $(PYTHON_INCLUDE) -o hello hello.c -isystem /Users/abhiksarkar/opt/anaconda3/lib/ -l /Users/abhiksarkar/opt/anaconda3/lib/ -arch x86_64